Sprint 09
PowerSl1d3/ImageFeed pull request #3
Opened 2023-04-02 11:23 UTC by PowerSl1d3

2023-04-02 12:31 UTC, mmbabaev commented on ImageFeed/Profile/ProfileViewController.swift
> +        view.addSubview(avatarImageView)
здесь пропущен вызов `super.viewDidLoad`

2023-04-02 12:31 UTC, mmbabaev commented on ImageFeed/Profile/ProfileViewController.swift
> +        view.addSubview(avatarImageView)
здесь пропущен вызов `super.viewDidLoad`

2023-04-02 12:34 UTC, mmbabaev requested changes

2023-04-02 12:34 UTC, mmbabaev commented on ImageFeed/Profile/ProfileViewController.swift
> +class ProfileViewController: UIViewController {
этот класс можно тоже сделать `final`

2023-04-02 12:34 UTC, mmbabaev commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +    override func viewDidLoad() {
здесь тоже пропущен вызов `super.viewDidLoad`

2023-04-02 12:34 UTC, mmbabaev commented on ImageFeed/ImageList/ImagesListViewController.swift
> +            let indexPath = sender as! IndexPath
не используйте force unwrap, разворачивайте безопасно переменные с помощью конструкций 
`if let`, `guard let`, `??`

2023-04-02 12:34 UTC, mmbabaev commented on ImageFeed/ImageList/ImagesListViewController.swift
> +            let indexPath = sender as! IndexPath
тут можно занести под if

2023-04-02 12:35 UTC, mmbabaev commented
<img width="301" alt="Screen Shot 2023-04-02 at 15 20 31" src="https://user-images.githubusercontent.com/12600807/229353099-e254cfbc-64e5-4617-bdcd-65b5624f63d8.png">
на этой картинке видно проблему с contentMode

2023-04-15 08:59 UTC, PowerSl1d3 commented
По поводу картинок - contentMode у них стоит в соответствии с материалами курса aspectFill.  По поводу того что на изображении видна черная полоса - это опять же такая картинка, можно посмотреть в ассетах
<img width="832" alt="image" src="https://user-images.githubusercontent.com/44105323/232202690-133b727b-892c-496a-94af-8c4614e06f12.png">

2023-04-15 09:09 UTC, PowerSl1d3 commented
Шрифты тоже поправил, но в некоторых частях на макетах, опять же, не везде проставлен нужен шрифт((
<img width="936" alt="image" src="https://user-images.githubusercontent.com/44105323/232203166-a1b45bc9-ecde-4dc0-9a8e-45dcdd827aaf.png">

2023-04-15 10:21 UTC, PowerSl1d3 commented
Помимо этого пришлось небольшой костыль вставить. 
<img width="512" alt="image" src="https://user-images.githubusercontent.com/44105323/232208069-765a5afa-3873-41c5-8089-11006fa5e141.png">
Шрифты почему то не хотят подтягиваться по нормальному, в IB всё ок, но в коде пустота. Пока в IB не проставишь шрифт в лейбле каком нибудь оно не заработает. Хз прикол ли это XCode-a или нет, но никакие другие способы не помогли решить проблему, поэтому на экране профиля один невидимый лейбл лежит

2023-04-15 16:21 UTC, mmbabaev commented
По шрифтам: попробуй "установить" шрифты, может в этом дело. У меня и без вспомогательного лейбла работают шрифты. 

Можно еще свериться с этой статьей
https://codewithchris.com/common-mistakes-with-adding-custom-fonts-to-your-ios-app/#includefonts

2023-04-16 02:17 UTC, merged